version: '3.8'
name: accessibility7-0
services:
    accessibility:
      container_name: accessibility7-0
      image: fargeo/accessibility7-0
      build:
        context: ..
        dockerfile: accessibility/Dockerfile
      command: run_arches
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/accessibility
      env_file:
        - ./docker/env_file.env
      ports:
        - 8018:8000
        - 5688:5678
      stdin_open: true
      tty: true

    accessibility-webpack:
      container_name: accessibility-webpack-7-0
      image: fargeo/accessibility-webpack-7-0
      build:
        context: ..
        dockerfile: accessibility/docker/webpack/Dockerfile
      command: run_webpack
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/accessibility
      env_file:
        - ./docker/webpack/env_file.env
      ports:
        - 8028:8021
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: arches7-0-dev

volumes:
    arches-log-accessibility7-0:
    arches-static-accessibility7-0:
